version: "3"

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ../dockerfiles/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: process.env.NODE_ENV
    volumes:
      - ../../../:/usr/app

  nginx:
    build:
      context: .
      dockerfile: ../dockerfiles/Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - frontend
    restart: always
