# syntax=docker/dockerfile:1

FROM node:16.10.0-alpine3.14 as base

LABEL version="1.0.0"
LABEL maintainer="Team_P"

FROM base as test
WORKDIR /usr/app
ENV NODE_ENV=test
COPY ["package.json", "package-lock.json", "./"]
RUN apk add --no-cache bash
RUN npm install -g craco
RUN npm ci --only=development
COPY . .
EXPOSE 3000
CMD ["npm", "run", "test"]
