# syntax=docker/dockerfile:1

FROM node:16.10.0-alpine3.14 as base

LABEL version="1.0.0"
LABEL maintainer="Team_P"

FROM base as dev
WORKDIR /usr/app
ENV NODE_ENV=development
COPY ["package.json", "package-lock.json", "./"]
RUN apk add --no-cache bash
RUN npm install -g craco
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start:dev"]

